### ISSUE TITLE
TypeError: WebSocketApp.__init__() got an unexpected keyword argument 'socket'

### ISSUE THREAD

**Issue by stephane-chazelas** [truenas/api_client#16]
With python3.10 and python-websocket 1.2.3 as found on Ubuntu 22.04:
```
$ midclt --uri ws://truenas.com/api/current call system.info
Traceback (most recent call last):
  File "/usr/bin/midclt", line 33, in <module>
    sys.exit(load_entry_point('truenas-api-client==0.0.0', 'console_scripts', 'midclt')())
  File "/usr/lib/python3/dist-packages/truenas_api_client/__init__.py", line 895, in main
    with Client(uri=args.uri) as c:
  File "/usr/lib/python3/dist-packages/truenas_api_client/__init__.py", line 93, in __init__
    self.__client = client_class(uri, reserved_ports, py_exceptions, log_py_exceptions, call_timeout, verify_ssl)
  File "/usr/lib/python3/dist-packages/truenas_api_client/__init__.py", line 443, in __init__
    self._ws.connect()
  File "/usr/lib/python3/dist-packages/truenas_api_client/__init__.py", line 158, in connect
    self.app = WebSocketApp(
TypeError: WebSocketApp.__init__() got an unexpected keyword argument 'socket'
```

The `socket` argument is only available since 1.3.2 (https://github.com/websocket-client/websocket-client/commit/1185fead98f674575d761ceb0137c4139a03eb34).

Ideally, that dependency should be specified, if only in the Debian `control` file.

**Comment by stephane-chazelas** [comment]
Thanks.

Sorry if that's a silly question as I'm not familiar with (nor generally big fan of) `python`, but shouldn't that dependency also be specified in the `setup.py`?
